[project]
name = "memutils"
version = "0.2.3"

[build]
clock_type = "posedge"
reset_type = "async_low"

sources = ["src"]
target = { type = "directory", path = "target" }

[test]
waveform_target = { type = "directory", path = "target/waveform" }
waveform_format = "fst"

[publish]
bump_commit = true
publish_commit = true